// <auto-generated />
namespace BlogSeymaCengiz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class initial8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial8));
        
        string IMigrationMetadata.Id
        {
            get { return "201506050049526_initial8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
